comments = [
    {
        "user_id": 1,
        "content": "This is a great answer!",
        "content_id": 1,
        "content_type": "answer",
    },
    {
        "user_id": 2,
        "content": "I completely agree with this explanation.",
        "content_id": 2,
        "content_type": "answer",
    },
    {
        "user_id": 3,
        "content": "Can you clarify this part?",
        "content_id": 3,
        "content_type": "answer",
    },
    {
        "user_id": 4,
        "content": "Thanks for sharing!",
        "content_id": 4,
        "content_type": "answer",
    },
    {
        "user_id": 5,
        "content": "I think there’s another way to do this.",
        "content_id": 5,
        "content_type": "answer",
    },
    {
        "user_id": 1,
        "content": "Very informative answer.",
        "content_id": 6,
        "content_type": "answer",
    },
    {"user_id": 2, "content": "Good point!", "content_id": 7, "content_type": "answer"},
    {
        "user_id": 3,
        "content": "This helped me a lot, thank you!",
        "content_id": 8,
        "content_type": "answer",
    },
    {
        "user_id": 4,
        "content": "Interesting perspective.",
        "content_id": 9,
        "content_type": "answer",
    },
    {
        "user_id": 5,
        "content": "I disagree; I think it works differently.",
        "content_id": 10,
        "content_type": "answer",
    },
    {
        "user_id": 1,
        "content": "Could you add more examples?",
        "content_id": 11,
        "content_type": "answer",
    },
    {
        "user_id": 2,
        "content": "This answer is well written.",
        "content_id": 12,
        "content_type": "answer",
    },
    {
        "user_id": 3,
        "content": "Nice explanation!",
        "content_id": 13,
        "content_type": "answer",
    },
    {
        "user_id": 4,
        "content": "I had the same question, thanks for this!",
        "content_id": 1,
        "content_type": "question",
    },
    {
        "user_id": 5,
        "content": "What a helpful answer.",
        "content_id": 2,
        "content_type": "question",
    },
    {
        "user_id": 1,
        "content": "I still don’t understand.",
        "content_id": 3,
        "content_type": "question",
    },
    {
        "user_id": 2,
        "content": "Where can I find more resources on this?",
        "content_id": 4,
        "content_type": "question",
    },
    {
        "user_id": 3,
        "content": "This is exactly what I needed.",
        "content_id": 5,
        "content_type": "question",
    },
    {
        "user_id": 4,
        "content": "Great explanation, thanks!",
        "content_id": 6,
        "content_type": "question",
    },
    {
        "user_id": 5,
        "content": "Please clarify the third step.",
        "content_id": 7,
        "content_type": "question",
    },
    {
        "user_id": 1,
        "content": "How does this compare to other methods?",
        "content_id": 8,
        "content_type": "question",
    },
    {
        "user_id": 2,
        "content": "This answer covers a lot, great job!",
        "content_id": 9,
        "content_type": "answer",
    },
    {
        "user_id": 3,
        "content": "I found a typo in the answer.",
        "content_id": 10,
        "content_type": "answer",
    },
    {
        "user_id": 4,
        "content": "Really liked this answer.",
        "content_id": 11,
        "content_type": "answer",
    },
    {
        "user_id": 5,
        "content": "The solution doesn’t work for me.",
        "content_id": 12,
        "content_type": "answer",
    },
    {
        "user_id": 1,
        "content": "Very thorough explanation.",
        "content_id": 13,
        "content_type": "answer",
    },
    {
        "user_id": 2,
        "content": "I’d suggest adding more context here.",
        "content_id": 1,
        "content_type": "question",
    },
    {
        "user_id": 3,
        "content": "This was a lifesaver, thanks!",
        "content_id": 2,
        "content_type": "question",
    },
    {
        "user_id": 4,
        "content": "Could you elaborate?",
        "content_id": 3,
        "content_type": "question",
    },
    {
        "user_id": 5,
        "content": "Is there an alternative approach?",
        "content_id": 4,
        "content_type": "question",
    },
    {
        "user_id": 1,
        "content": "I had a similar question before.",
        "content_id": 5,
        "content_type": "question",
    },
    {
        "user_id": 2,
        "content": "I’ll try this out, thanks!",
        "content_id": 6,
        "content_type": "question",
    },
    {
        "user_id": 3,
        "content": "Great tip!",
        "content_id": 7,
        "content_type": "question",
    },
    {
        "user_id": 4,
        "content": "Just what I needed.",
        "content_id": 8,
        "content_type": "question",
    },
    {
        "user_id": 5,
        "content": "Perfect solution.",
        "content_id": 9,
        "content_type": "question",
    },
    {
        "user_id": 1,
        "content": "I’ll give this a try.",
        "content_id": 10,
        "content_type": "question",
    },
    {
        "user_id": 2,
        "content": "This answer was very insightful.",
        "content_id": 11,
        "content_type": "answer",
    },
    {
        "user_id": 3,
        "content": "Can we use this approach in production?",
        "content_id": 12,
        "content_type": "answer",
    },
    {
        "user_id": 4,
        "content": "I’ve tried this and it worked!",
        "content_id": 13,
        "content_type": "answer",
    },
    {
        "user_id": 5,
        "content": "Does this work for all cases?",
        "content_id": 1,
        "content_type": "answer",
    },
]
