tags = [
    {"name": "Python"},
    {"name": "JavaScript"},
    {"name": "Flask"},
    {"name": "Django"},
    {"name": "SQLAlchemy"},
    {"name": "React"},
    {"name": "Node.js"},
    {"name": "Express"},
    {"name": "HTML"},
    {"name": "CSS"},
    {"name": "Bootstrap"},
    {"name": "API"},
    {"name": "REST"},
    {"name": "GraphQL"},
    {"name": "MongoDB"},
    {"name": "PostgreSQL"},
    {"name": "MySQL"},
    {"name": "Redis"},
    {"name": "Docker"},
    {"name": "Kubernetes"},
    {"name": "Git"},
    {"name": "GitHub"},
    {"name": "AWS"},
    {"name": "Azure"},
    {"name": "Firebase"},
    {"name": "Machine Learning"},
    {"name": "Data Science"},
    {"name": "Artificial Intelligence"},
    {"name": "Web Development"},
    {"name": "Software Testing"},
    {"name": "DevOps"},
]
