users = [
    {
        "username": "admin",
        "email": "admin@admin.com",
        "first_name": "Adam",
        "last_name": "In",
        "password": "adminadmin",
    },
    {
        "username": "john_doe",
        "email": "john@example.com",
        "first_name": "John",
        "last_name": "Doe",
        "password": "password123",
    },
    {
        "username": "jane_smith",
        "email": "jane@example.com",
        "first_name": "Jane",
        "last_name": "Smith",
        "password": "securepassword",
    },
    {
        "username": "alice_wonder",
        "email": "alice@example.com",
        "first_name": "Alice",
        "last_name": "Wonderland",
        "password": "wonderland123",
    },
    {
        "username": "mike_ross",
        "email": "mike@example.com",
        "first_name": "Mike",
        "last_name": "Ross",
        "password": "harvey123",
    },
    {
        "username": "lisa_kudrow",
        "email": "lisa@example.com",
        "first_name": "Lisa",
        "last_name": "Kudrow",
        "password": "phoebe123",
    },
    {
        "username": "rick_sanchez",
        "email": "rick@example.com",
        "first_name": "Rick",
        "last_name": "Sanchez",
        "password": "portal123",
    },
    {
        "username": "morty_smith",
        "email": "morty@example.com",
        "first_name": "Morty",
        "last_name": "Smith",
        "password": "adventure",
    },
    {
        "username": "peter_parker",
        "email": "peter@example.com",
        "first_name": "Peter",
        "last_name": "Parker",
        "password": "spiderman",
    },
    {
        "username": "bruce_wayne",
        "email": "bruce@example.com",
        "first_name": "Bruce",
        "last_name": "Wayne",
        "password": "batman",
    },
    {
        "username": "clark_kent",
        "email": "clark@example.com",
        "first_name": "Clark",
        "last_name": "Kent",
        "password": "superman",
    },
    {
        "username": "diana_prince",
        "email": "diana@example.com",
        "first_name": "Diana",
        "last_name": "Prince",
        "password": "wonderwoman",
    },
    {
        "username": "tony_stark",
        "email": "tony@example.com",
        "first_name": "Tony",
        "last_name": "Stark",
        "password": "ironman",
    },
    {
        "username": "natasha_romanoff",
        "email": "natasha@example.com",
        "first_name": "Natasha",
        "last_name": "Romanoff",
        "password": "blackwidow",
    },
    {
        "username": "steve_rogers",
        "email": "steve@example.com",
        "first_name": "Steve",
        "last_name": "Rogers",
        "password": "captain",
    },
    {
        "username": "bruce_banner",
        "email": "bruce.banner@example.com",
        "first_name": "Bruce",
        "last_name": "Banner",
        "password": "hulk",
    },
    {
        "username": "wanda_maximoff",
        "email": "wanda@example.com",
        "first_name": "Wanda",
        "last_name": "Maximoff",
        "password": "scarlet",
    },
    {
        "username": "scott_lang",
        "email": "scott@example.com",
        "first_name": "Scott",
        "last_name": "Lang",
        "password": "antman",
    },
    {
        "username": "t_challa",
        "email": "tchalla@example.com",
        "first_name": "T'Challa",
        "last_name": "Unknown",
        "password": "blackpanther",
    },
    {
        "username": "sam_wilson",
        "email": "sam@example.com",
        "first_name": "Sam",
        "last_name": "Wilson",
        "password": "falcon",
    },
    {
        "username": "bucky_barnes",
        "email": "bucky@example.com",
        "first_name": "Bucky",
        "last_name": "Barnes",
        "password": "winter",
    },
    {
        "username": "carol_danvers",
        "email": "carol@example.com",
        "first_name": "Carol",
        "last_name": "Danvers",
        "password": "captainmarvel",
    },
    {
        "username": "peter_quill",
        "email": "peter.quill@example.com",
        "first_name": "Peter",
        "last_name": "Quill",
        "password": "starlord",
    },
    {
        "username": "gamora",
        "email": "gamora@example.com",
        "first_name": "Gamora",
        "last_name": "Zen Whoberi Ben Titan",
        "password": "daughter",
    },
    {
        "username": "drax_destroyer",
        "email": "drax@example.com",
        "first_name": "Drax",
        "last_name": "Destroyer",
        "password": "invisible",
    },
]
