"""add votes model/relations

Revision ID: 2cb1a8e4e5d9
Revises: a6724852264c
Create Date: 2024-11-04 15:34:34.922066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb1a8e4e5d9'
down_revision = 'a6724852264c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('value IN (-1, 0, 1)', name='check_vote_value'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('total_score')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('total_score')

    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_column('total_score')

    op.drop_table('votes')
    # ### end Alembic commands ###
