"""add_parent_type_to_save_model

Revision ID: a6724852264c
Revises: ba6392cf41e0
Create Date: 2024-11-03 17:04:10.236851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6724852264c'
down_revision = 'ba6392cf41e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saves', schema=None) as batch_op:
        batch_op.drop_column('parent_type')

    # ### end Alembic commands ###
